language: cpp
compiler:
    - g++
os:
    - linux

before_install:
    - sudo apt-get install libfftw3-dev libfftw3-doc
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8"

script:
    - cd catch-tests
    - make
    - ./test_CROM.o
