sudo: required
language: cpp
compiler:
    - g++
os:
    - linux
notifications:
    email: false

before_install:
    - sudo apt-get install libfftw3-dev libfftw3-doc

script:
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    - gcc --version
    - cd catch-tests
    - make
    - ./test_CROM.o
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-5
            - g++-5
