all:
	g++ test_CROM_full.cpp ../../encoder/CROM_encoder.cpp ../../decoder/CROM_decoder.cpp ../../utils/matrix_multiplication.cpp ../../utils/CROM_util.cpp -L/usr/local/lib -I/usr/local/include -lfftw3 -o test_CROM.o -lm
